name: ${project.artifactId}
main: eu.internetpolice.potionhappiness.${project.artifactId}
version: ${project.version}
author: "internetpolice.eu"
api-version: 1.15
commands:
  potions:
    description: Toggles potion effects
    usage: /potions [target user] (potiontype) [on|off]
